name: converter_plus_plus
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.2.1
  file_picker: ^5.2.3
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.2

flutter:

  uses-material-design: true

#  assets:
#   - assets/ffmpeg/ffprobe.exe